package io.github.y15173334444.create_schematic_compute.blocks;

import net.minecraft.core.Direction;

/**
 * 动力传感器朝向语义 + 屏幕锚点的**单一真相源**。
 * Single source of truth for the kinetic gauge's orientation semantics and screen anchors.
 *
 * <p>这里住着三样东西，它们此前散落在三处（生成脚本 / blockstate JSON / 渲染器）：
 * <ol>
 *   <li>{@link #useShaftYVariant} —— 12 个状态里哪 4 个走 {@code _shaft_y} 模型；</li>
 *   <li>{@link #xRotation}/{@link #yRotation} —— BER 复刻 blockstate 的旋转角；</li>
 *   <li>{@link #PANEL_BASE}/{@link #PANEL_SHAFT_Y} —— 蓝屏绘制锚点（authored 模型空间 0..16）。</li>
 * </ol>
 * 三者必须与 {@code blockstates/kinetic_gauge.json}（由
 * {@code tools/gen_gauge_assets.py} 生成）逐项一致，一致性由
 * {@code src/test/.../blocks/KineticGaugeStatesTest} 钉死 —— 改这里就要跑测试。</p>
 * <p>Three things live here, previously spread over three artefacts (generator script /
 * blockstate JSON / renderer): which 4 of the 12 states use the {@code _shaft_y} model,
 * the blockstate x/y rotations the BER replays, and the blue-screen draw anchors. All three
 * must match {@code blockstates/kinetic_gauge.json} (generated by
 * {@code tools/gen_gauge_assets.py}); {@code KineticGaugeStatesTest} pins that down.</p>
 *
 * <p><b>纯类 / pure class</b>：只依赖 {@link Direction}，不引用任何客户端类型 —— 因此可以在
 * 服务端路径与单元测试里安全使用（{@code DedicatedServerClientRefTest} 约束）。</p>
 * <p>Depends on {@link Direction} only — no client types — so it is safe on server paths and
 * in unit tests.</p>
 */
public final class KineticGaugeStates {

    private KineticGaugeStates() {}

    /**
     * 屏幕面板锚点（authored 模型空间 0..16）。BER 在平移到块中心后以
     * {@code (x-8, y-8, z-8)} 使用。
     * Screen panel anchor in authored model space 0..16 (the BER uses it as
     * {@code (x-8, y-8, z-8)} after translating to the block centre).
     *
     * @param cx,cy,cz       屏幕中心（authored 空间）/ panel centre
     * @param nx,ny,nz       屏幕外法线（单位向量）/ outward normal (unit)
     * @param rx,ry,rz       文字右方向（单位向量）/ text right direction (unit)
     * @param ux,uy,uz       文字上方向（单位向量）/ text up direction (unit)
     * @param halfRight,halfUp 排版窗口半宽/半高（模型单位）/ layout half-width / half-height
     */
    public record Panel(float cx, float cy, float cz,
                        float nx, float ny, float nz,
                        float rx, float ry, float rz,
                        float ux, float uy, float uz,
                        float halfRight, float halfUp) {}

    /**
     * 基础变体：讲台屏（法线上仰 45° 朝西），蓝面 8×16、去导轨/封头后可用 ≈14×6.6。
     * Base variant: lectern screen (normal tilted 45° up-west); the 8×16 blue face leaves
     * ≈14×6.6 usable after the rails/end caps.
     */
    public static final Panel PANEL_BASE = new Panel(
        3.5556f - 0.02f, 12.3841f + 0.02f, 8f,   // 中心沿法线外提 0.02 防 z-fight / 0.02 along the normal against z-fighting
        -0.7071f, 0.7071f, 0f,
        0f, 0f, 1f,
        0.7071f, 0.7071f, 0f,
        7.0f, 3.3f);

    /**
     * 竖直轴变体（手绘）：斜 45° 的竖直屏，法线朝**西北**（`screen` 元素的两个大面里朝外的那个），
     * 版面 8×16 竖屏、排版窗口 7.6×15。
     * Vertical-shaft variant (hand-modelled): a 45°-yawed vertical panel whose normal points
     * **north-west** (the outward of the `screen` element's two large faces); portrait 8×16 face,
     * 7.6×15 layout window.
     *
     * <p>数值由 {@code tools/gen_gauge_assets.py} 从模型反算（中心沿法线外提 0.02 防 z-fight），
     * 由 {@code KineticGaugeStatesTest} 钉在模型几何上。halfRight/halfUp 取**被框沿遮挡后真正可见的
     * 范围**（脚本会打印 unoccluded span）—— 面本身是 8×16，但四条 bezel 各盖掉边上的 1 单位，
     * 可见区只剩 5.7×13.7（半宽 2.85 / 半高 6.85）；窗口超出它就会把文字/进度条压到框沿上
     * （2026-09-13 实测："超出左右一点点"）。</p>
     * <p>Derived from the model by {@code tools/gen_gauge_assets.py} and pinned by
     * {@code KineticGaugeStatesTest}. halfRight/halfUp use the **unoccluded** span: the face is 8×16
     * but the four bezel elements cover 1 unit on each edge, leaving 5.7×13.7 (half 2.85 / 6.85).</p>
     */
    public static final Panel PANEL_SHAFT_Y = new Panel(
        3.5574f - 0.02f, 8f, 3.6142f - 0.02f,
        -0.7071f, 0f, -0.7071f,
        -0.7071f, 0f, 0.7071f,
        0f, 1f, 0f,
        2.85f, 6.85f);

    /**
     * 自由放置（未贴着带轴的面）时的显示面朝向 —— 即 {@code facing} 属性。
     * Display direction ({@code facing}) for free placement (not against a shaft-bearing face).
     *
     * <p><b>贴墙</b>：显示面 = 点击面（玩家只能点到自己面前那一面）。</p>
     * <p><b>贴地/贴顶</b>：取 {@code 视线反向}（= Create 官方 {@code DirectionalKineticBlock} 的规则）。
     * 于是同一条规则同时给出两种被要过的行为：平视放置 → 显示面水平朝向玩家（四向可选，修复"贴地只有
     * 两向"）；<b>俯视地面 / 仰视天花板放置 → 显示面朝上 / 朝下</b>（"竖置"状态可直接放出 —— 2026-09-13
     * 实测回归：改前用水平视线反向，导致竖置只能靠扳手转出来）。</p>
     * <p><b>Wall</b>: display = clicked face. <b>Floor/ceiling</b>: the inverted nearest-looking
     * direction (Create's official rule), so a horizontal look gives a horizontal, player-facing
     * display while a steeply down/up look gives the display facing up/down — the vertical state is
     * directly placeable again.</p>
     *
     * @param clickedFace    {@code ctx.getClickedFace()} / the clicked face
     * @param nearestLooking {@code ctx.getNearestLookingDirection()} / nearest looking direction
     * @return {@code facing}（水平或竖直）/ the facing
     */
    public static Direction facingForPlacement(Direction clickedFace, Direction nearestLooking) {
        // 贴墙：显示面 = 点击面（官方表语义；玩家只能点到自己面前那一面，故等价于"正对玩家"）。
        // On a wall: display = clicked face (official semantics).
        if (clickedFace.getAxis().isHorizontal())
            return clickedFace;
        // 贴地/贴顶：视线反向 —— 平视得到水平朝向，俯视/仰视得到 up/down（竖置可直接放置）。
        // Floor/ceiling: inverted look — horizontal for a level look, up/down for a steep look.
        return nearestLooking.getOpposite();
    }

    /**
     * 扳手点击面的动作分类（**纯函数**，可单测）。
     * Classification of a wrench click (pure function, unit-testable).
     *
     * <p>{@link WrenchAction#CYCLE_DISPLAY}：屏幕绕轴循环 90°（轴与传动连接不动）—— 包含
     * ①<b>轴端面</b>（点击轴 ∥ 旋转轴）与 ②<b>屏幕正前方</b>（{@link #isDisplayFace}，45° 倾斜/
     * 斜偏的面板会有两个面）。</p>
     * <p>{@link WrenchAction#RIGID_ROTATE}：其余两个面 → 整表刚性旋转一格（轴绕点击轴 90°）。</p>
     * <p><b>轴端面为什么是 90° 而不是 180°</b>：<b>Create 本身就是"点端面绕轴 90° 转"</b>
     * （作者指正 2026-09-13）—— 与机械动力的肌肉记忆一致优先；180° 只是连点两格，不需要单独分支。</p>
     * <p>Why the shaft end face cycles 90° rather than flipping 180°: <b>Create itself rotates a block
     * 90° around its end face</b> (author correction 2026-09-13) — matching Create's muscle memory
     * wins, and a 180° flip is just two 90° steps.</p>
     */
    public enum WrenchAction { CYCLE_DISPLAY, RIGID_ROTATE }

    /**
     * @param shaft       {@code getRotationAxis(state)} / this block's rotation axis
     * @param facing      {@code FACING} / display direction
     * @param alongFirst  {@code AXIS_ALONG_FIRST_COORDINATE} / axis decomposition bit
     * @param clickedFace the face the wrench clicked / 扳手点击的面
     */
    public static WrenchAction wrenchAction(Direction.Axis shaft, Direction facing, boolean alongFirst,
                                            Direction clickedFace) {
        if (clickedFace.getAxis() == shaft) return WrenchAction.CYCLE_DISPLAY;                 // 轴端面
        if (isDisplayFace(facing, alongFirst, clickedFace)) return WrenchAction.CYCLE_DISPLAY; // 屏幕正前方
        return WrenchAction.RIGID_ROTATE;
    }

    /**
     * 面板在世界（blockstate 已旋转）空间的**朝外法线** —— 与渲染器 / 贴图旋转同一套约定
     * （blockstate：x 先 y 后，原版"从正轴看顺时针"= 左手系）。
     * The panel's outward normal in world space (blockstate rotations applied), same convention as
     * the renderer.
     */
    public static float[] panelNormalWorld(Direction facing, boolean alongFirst) {
        Panel p = useShaftYVariant(facing, alongFirst) ? PANEL_SHAFT_Y : PANEL_BASE;
        float nx = p.nx(), ny = p.ny(), nz = p.nz();
        if (xRotation(facing) == 180) {          // x 旋转：本表只出现 180 → (x,−y,−z)
            ny = -ny;
            nz = -nz;
        }
        int y = ((yRotation(facing, alongFirst) % 360) + 360) % 360;
        float tx, tz;
        switch (y) {
            case 90  -> { tx = -nz; tz = nx; }    // y=90:  (x,y,z) -> (−z, y, x)
            case 180 -> { tx = -nx; tz = -nz; }
            case 270 -> { tx = nz; tz = -nx; }
            default  -> { tx = nx; tz = nz; }
        }
        return new float[]{tx, ny, tz};
    }

    /**
     * 这个面是否"在屏幕正前方"（点它就当作点屏幕 → 扳手绕轴循环显示方向）。
     * Whether the clicked face is on the display side (clicking it counts as clicking the screen).
     *
     * <p>用点积而不是 {@code clickedFace == facing}：面板可能是**倾斜 45°（基础变体）**或
     * **绕 Y 偏 45°（手绘竖版）**的，此时"屏幕正前方"落在两个方块面之间，会有**两个**面同时正对
     * 屏幕 —— 只认一个会让另一个被当成侧面而触发整表刚性旋转（轴跟着转）。2026-09-13 实测回归：
     * 竖置状态用扳手转屏幕"只能 180°"。</p>
     * <p>Uses a dot product rather than {@code clickedFace == facing}: with a 45°-tilted or
     * 45°-yawed panel two block faces can both be "in front" of the screen, and recognising only one
     * makes the other rotate the whole gauge (shaft included).</p>
     */
    public static boolean isDisplayFace(Direction facing, boolean alongFirst, Direction clickedFace) {
        float[] n = panelNormalWorld(facing, alongFirst);
        Direction.Axis a = clickedFace.getAxis();
        float c = a == Direction.Axis.X ? n[0] : a == Direction.Axis.Y ? n[1] : n[2];
        return c * clickedFace.getAxisDirection().getStep() > 0.5f;
    }

    /**
     * 竖直轴 4 态走 {@code _shaft_y} 变体（north/south A=false、east/west A=true）。
     * 与 {@code blockstates/kinetic_gauge.json} 的模型选择逐项一致。
     * The 4 vertical-shaft states use the {@code _shaft_y} variant (north/south with
     * A=false, east/west with A=true) — mirrors the blockstate JSON's model choice.
     */
    public static boolean useShaftYVariant(Direction facing, boolean alongFirst) {
        return switch (facing) {
            case NORTH, SOUTH -> !alongFirst;
            case EAST, WEST -> alongFirst;
            default -> false;
        };
    }

    /**
     * 面板基矩阵：字形空间（x 右 / y 下 / 可读侧 −Z）→ 模型空间（居中于方块）。
     * Panel basis matrix: glyph space (x right / y down / readable side −Z) -> model units centred
     * in the block.
     *
     * <p><b>JOML 的 16 参数 {@code set(...)} 是列主序</b>（前 4 个参数填第 1 列），所以这里**按列分组**
     * 传入；写成"行主序"会把整个矩阵转置 —— 平移落进底行（透视行），GPU 做透视除法后顶点被 w 除成
     * 怪值，实机表现为"面条一路拉到相机"（2026-09-13 实证，见 {@code KineticGaugeStatesTest}）。</p>
     * <p>JOML's 16-argument {@code set(...)} is <b>column-major</b>, hence the per-column grouping.
     * Writing it row-major transposes the matrix, pushes the translation into the perspective row and
     * the GPU then divides vertices by w — "noodles stretching to the camera" in game.</p>
     *
     * <p>列 = {@code [right, −up, −normal, translation]}，平移为 {@code (cx−8, cy−8, cz−8)}（模型单位）。</p>
     * <p>Columns are {@code [right, −up, −normal, translation]} in model units.</p>
     */
    public static org.joml.Matrix4f panelBasis(Panel p) {
        return new org.joml.Matrix4f().set(
            p.rx(), p.ry(), p.rz(), 0f,
            -p.ux(), -p.uy(), -p.uz(), 0f,
            -p.nx(), -p.ny(), -p.nz(), 0f,
            p.cx() - 8f, p.cy() - 8f, p.cz() - 8f, 1f);
    }

    /** blockstate x 旋转：仅 down 状态翻 180。/ blockstate x rotation: only DOWN flips 180. */
    public static int xRotation(Direction facing) {
        return facing == Direction.DOWN ? 180 : 0;
    }

    /** blockstate y 旋转（与 JSON 表一致）。/ blockstate y rotation (matches the JSON table). */
    public static int yRotation(Direction facing, boolean alongFirst) {
        return switch (facing) {
            case NORTH -> 90;
            case SOUTH -> 270;
            case EAST -> 180;
            case WEST -> 0;
            case UP, DOWN -> alongFirst ? 90 : 0;
        };
    }
}
