package io.github.y15173334444.create_schematic_compute.blocks;

import net.minecraft.core.Direction;

/**
 * 动力传感器朝向语义 + 屏幕锚点的**单一真相源**。
 * Single source of truth for the kinetic gauge's orientation semantics and screen anchors.
 *
 * <p>这里住着四样东西，它们此前散落在多处（生成脚本 / blockstate JSON / 渲染器 / 方块类）：
 * <ol>
 *   <li>{@link #useShaftYVariant} —— 12 个状态里哪 4 个走 {@code _shaft_y} 模型；</li>
 *   <li>{@link #xRotation}/{@link #yRotation} —— BER 复刻 blockstate 的旋转角；</li>
 *   <li>{@link #PANEL_BASE}/{@link #PANEL_SHAFT_Y} —— 蓝屏绘制锚点（authored 模型空间 0..16），
 *   实际渲染入口是 {@link #displayPanel}（含倒置态的文字 180° 翻正）；</li>
 *   <li>{@link #nextInShaftRoll}/{@link #nextInYaw} —— 扳手同轴滚转环与偏航环
 *   （纯函数，可单测；顺序与方向由 {@code KineticGaugePlacementTest} 钉死）。</li>
 * </ol>
 * 三者必须与 {@code blockstates/kinetic_gauge.json}（由
 * {@code tools/gen_gauge_assets.py} 生成）逐项一致，一致性由
 * {@code src/test/.../blocks/KineticGaugeStatesTest} 钉死 —— 改这里就要跑测试。</p>
 * <p>Four things live here, previously spread over several artefacts (generator script /
 * blockstate JSON / renderer / block class): which 4 of the 12 states use the {@code _shaft_y}
 * model, the blockstate x/y rotations the BER replays, and the blue-screen draw anchors
 * (rendered via {@link #displayPanel}, which un-inverts text on inverted poses) — plus the
 * wrench's roll/yaw rings ({@link #nextInShaftRoll}/{@link #nextInYaw}). The first three
 * must match {@code blockstates/kinetic_gauge.json} (generated by
 * {@code tools/gen_gauge_assets.py}); {@code KineticGaugeStatesTest} pins that down.</p>
 *
 * <p><b>纯类 / pure class</b>：只依赖 {@link Direction}，不引用任何客户端类型 —— 因此可以在
 * 服务端路径与单元测试里安全使用（{@code DedicatedServerClientRefTest} 约束）。</p>
 * <p>Depends on {@link Direction} only — no client types — so it is safe on server paths and
 * in unit tests.</p>
 */
public final class KineticGaugeStates {

    private KineticGaugeStates() {}

    /**
     * 屏幕面板锚点（authored 模型空间 0..16）。BER 在平移到块中心后以
     * {@code (x-8, y-8, z-8)} 使用。
     * Screen panel anchor in authored model space 0..16 (the BER uses it as
     * {@code (x-8, y-8, z-8)} after translating to the block centre).
     *
     * @param cx,cy,cz       屏幕中心（authored 空间）/ panel centre
     * @param nx,ny,nz       屏幕外法线（单位向量）/ outward normal (unit)
     * @param rx,ry,rz       文字右方向（单位向量）/ text right direction (unit)
     * @param ux,uy,uz       文字上方向（单位向量）/ text up direction (unit)
     * @param halfRight,halfUp 排版窗口半宽/半高（模型单位）/ layout half-width / half-height
     */
    public record Panel(float cx, float cy, float cz,
                        float nx, float ny, float nz,
                        float rx, float ry, float rz,
                        float ux, float uy, float uz,
                        float halfRight, float halfUp) {

        /**
         * 字形右/上在面板平面内转 180°（法线不动，右手系保持：
         * {@code (−r) × (−u) = r × u = n}）。用于倒置态（facing 为竖直、blockstate
         * {@code x:180}）时抵消文字倒置。
         * Rotate the glyph right/up 180° in the panel plane (normal untouched; still
         * right-handed). Cancels the text inversion of the inverted poses (vertical
         * facing, blockstate {@code x:180}).
         */
        public Panel withTextRotated180() {
            return new Panel(cx, cy, cz, nx, ny, nz, -rx, -ry, -rz, -ux, -uy, -uz,
                halfRight, halfUp);
        }
    }

    /**
     * 基础变体：讲台屏（法线上仰 45° 朝西），蓝面 8×16、去导轨/封头后可用 ≈14×6.6。
     * Base variant: lectern screen (normal tilted 45° up-west); the 8×16 blue face leaves
     * ≈14×6.6 usable after the rails/end caps.
     */
    public static final Panel PANEL_BASE = new Panel(
        3.5556f - 0.02f, 12.3841f + 0.02f, 8f,   // 中心沿法线外提 0.02 防 z-fight / 0.02 along the normal against z-fighting
        -0.7071f, 0.7071f, 0f,
        0f, 0f, 1f,
        0.7071f, 0.7071f, 0f,
        7.0f, 3.3f);

    /**
     * 竖直轴变体（手绘）：斜 45° 的竖直屏，法线朝**西北**（`screen` 元素的两个大面里朝外的那个），
     * 版面 8×16 竖屏、排版窗口 7.6×15。
     * Vertical-shaft variant (hand-modelled): a 45°-yawed vertical panel whose normal points
     * **north-west** (the outward of the `screen` element's two large faces); portrait 8×16 face,
     * 7.6×15 layout window.
     *
     * <p>数值由 {@code tools/gen_gauge_assets.py} 从模型反算（中心沿法线外提 0.02 防 z-fight），
     * 由 {@code KineticGaugeStatesTest} 钉在模型几何上。halfRight/halfUp 取**被框沿遮挡后真正可见的
     * 范围**（脚本会打印 unoccluded span）—— 面本身是 8×16，但四条 bezel 各盖掉边上的 1 单位，
     * 可见区只剩 5.7×13.7（半宽 2.85 / 半高 6.85）；窗口超出它就会把文字/进度条压到框沿上
     * （2026-09-13 实测："超出左右一点点"）。</p>
     * <p>Derived from the model by {@code tools/gen_gauge_assets.py} and pinned by
     * {@code KineticGaugeStatesTest}. halfRight/halfUp use the **unoccluded** span: the face is 8×16
     * but the four bezel elements cover 1 unit on each edge, leaving 5.7×13.7 (half 2.85 / 6.85).</p>
     */
    public static final Panel PANEL_SHAFT_Y = new Panel(
        3.5574f - 0.02f, 8f, 3.6142f - 0.02f,
        -0.7071f, 0f, -0.7071f,
        -0.7071f, 0f, 0.7071f,
        0f, 1f, 0f,
        2.85f, 6.85f);

    /**
     * 自由放置（未贴着带轴的面）时的显示面朝向 —— 即 {@code facing} 属性（**恒为水平**）。
     * Display direction ({@code facing}) for free placement (not against a shaft-bearing
     * face) — always horizontal.
     *
     * <p><b>贴墙</b>：显示面 = 点击面（玩家只能点到自己面前那一面）。</p>
     * <p><b>贴地/贴顶</b>：水平正对玩家。2026-09 实机定为：facing 不再因俯视/仰视变成
     * up/down（那只剩 along_first 一个自由度，换不出 4 个偏航角）——竖置改由
     * <b>竖直轴</b>表达（陡视时调用方选 {@link #alongFirstForVerticalShaft}，
     * 平视时为横置讲台），由调用方的陡视门控决定。</p>
     * <p><b>Wall</b>: display = clicked face. <b>Floor/ceiling</b>: horizontally toward the
     * player. facing no longer becomes up/down on steep looks (that leaves a single
     * degree of freedom — two states cannot encode four yaws); the vertical pose is
     * expressed by a <b>vertical shaft</b> instead, chosen by the caller's steep-look gate.</p>
     *
     * @param clickedFace    {@code ctx.getClickedFace()} / the clicked face
     * @param nearestLooking {@code ctx.getNearestLookingDirection()} / nearest looking direction
     * @return {@code facing}（恒为水平）/ the facing, always horizontal
     */
    public static Direction facingForPlacement(Direction clickedFace, Direction nearestLooking) {
        // 测试便捷重载：把 nearestLooking 同时当作水平视线（贴墙时第三参不参与，安全）。
        // Test convenience: reuse nearestLooking as the horizontal look (unused on wall clicks).
        return facingForPlacement(clickedFace, nearestLooking, nearestLooking);
    }

    /**
     * @param horizontalLooking {@code ctx.getHorizontalDirection()} / the player's horizontal look
     */
    public static Direction facingForPlacement(Direction clickedFace, Direction nearestLooking,
                                              Direction horizontalLooking) {
        // 贴墙：显示面 = 点击面（官方表语义）。
        // On a wall: display = clicked face (official semantics).
        if (clickedFace.getAxis().isHorizontal())
            return clickedFace;
        // 贴地/贴顶：视线反向；俯视/仰视（反向为竖直）时退回水平视线反向 —— facing 恒水平，
        // 竖置与否（横置讲台 / 竖直轴平板）由调用方的陡视门控决定 along_first。
        // Floor/ceiling: inverted nearest look; a vertical result falls back to the
        // inverted horizontal look — facing stays horizontal, and whether the pose is a
        // lectern or a vertical-shaft panel is the caller's steep-look gate on along_first.
        Direction look = nearestLooking.getOpposite();
        return look.getAxis().isHorizontal() ? look : horizontalLooking.getOpposite();
    }

    /**
     * 竖置（竖直轴）的 {@code axis_along_first}：facing E/W → true，N/S → false。
     * {@code axis_along_first} for a vertical shaft: true for E/W facing, false for N/S.
     */
    public static boolean alongFirstForVerticalShaft(Direction facing) {
        return facing.getAxis() == Direction.Axis.X;
    }

    /**
     * 渲染用面板锚点：取变体后，在倒置态（facing 为竖直、blockstate {@code x:180}）时
     * 把字形右/上在面板平面内转 180° —— 否则整机翻下去后从屏幕外侧看文字是倒的
     * （2026-09 实测：倒置挂墙/朝下时蓝屏朝下正确，但读数上下颠倒）。
     * Panel anchor for rendering: pick the variant, then spin the glyph right/up 180° in
     * the panel plane for the inverted poses (vertical facing, blockstate {@code x:180}) —
     * otherwise an inverted mount shows the readout upside-down even though the
     * blue face correctly points downward.
     */
    public static Panel displayPanel(Direction facing, boolean alongFirst) {
        Panel p = useShaftYVariant(facing, alongFirst) ? PANEL_SHAFT_Y : PANEL_BASE;
        return xRotation(facing, alongFirst) == 180 ? p.withTextRotated180() : p;
    }

    /**
     * 面板在世界（blockstate 已旋转）空间的朝外法线 —— 朝向语义的几何定义，
     * 测试用它当几何预言机（环序 90° 步进、文字朝上等钉子都从它推）。
     * The panel's outward normal in world space (blockstate rotations applied) — the
     * geometric definition of the orientation semantics; tests use it as the geometry
     * oracle for the ring-order and text-upright pins.
     */
    public static float[] panelNormalWorld(Direction facing, boolean alongFirst) {
        Panel p = useShaftYVariant(facing, alongFirst) ? PANEL_SHAFT_Y : PANEL_BASE;
        float nx = p.nx(), ny = p.ny(), nz = p.nz();
        if (xRotation(facing, alongFirst) == 180) {
            ny = -ny;
            nz = -nz;
        }
        int y = ((yRotation(facing, alongFirst) % 360) + 360) % 360;
        float tx, tz;
        switch (y) {
            case 90  -> { tx = -nz; tz = nx; }
            case 180 -> { tx = -nx; tz = -nz; }
            case 270 -> { tx = nz; tz = -nx; }
            default  -> { tx = nx; tz = nz; }
        }
        return new float[]{tx, ny, tz};
    }

    /** 扳手迁移目标：一个 {@code (facing, axis_along_first)} 对。/ A wrench transition target. */
    public record WrenchTarget(Direction facing, boolean alongFirst) {}

    /**
     * 轴端面点击：同轴四态按角点序（右上→右下→左下→左上）滚转 90°，轴不动。
     * 每步法线恰绕 {@code shaft} 转 90°、与 {@link Direction#getClockWise(shaft)} 同向 ——
     * 环序错一格就会出 180° 对角跳（2026-09-26 实机：Y 环曾 NW→SW→NE→SE 半跳）。
     * 三个环按轴划分 12 态，故 (facing, alongFirst) 必在环上；返回 null 仅为未来改动兜底。
     * Shaft-end click: roll through the four same-shaft states in corner order, 90° per step
     * about {@code shaft}, following {@code getClockWise(shaft)}. A mis-ordered ring yields
     * 180° diagonal hops (the Y ring shipped that way once). The three rings partition the
     * 12 states by shaft, so the pair is always on the ring; null is future-proofing only.
     */
    public static WrenchTarget nextInShaftRoll(Direction facing, boolean alongFirst,
                                               Direction.Axis shaft) {
        WrenchTarget[] cycle = switch (shaft) {
            // 轴 Z：up+false(down-E) → down+false(down-W) → west+false(up-W) → east+false(up-E)
            case Z -> new WrenchTarget[]{
                new WrenchTarget(Direction.UP, false),
                new WrenchTarget(Direction.DOWN, false),
                new WrenchTarget(Direction.WEST, false),
                new WrenchTarget(Direction.EAST, false)};
            // 轴 X：up+true(down-N) → down+true(down-S) → south+true(up-S) → north+true(up-N)
            case X -> new WrenchTarget[]{
                new WrenchTarget(Direction.UP, true),
                new WrenchTarget(Direction.DOWN, true),
                new WrenchTarget(Direction.SOUTH, true),
                new WrenchTarget(Direction.NORTH, true)};
            // 轴 Y（平板屏绕竖轴偏航）：west+true(NW) → north+false(NE) → east+true(SE) → south+false(SW)
            // —— 2026-09-26 修正：曾写成 NW→SW→NE→SE，第 2/4 步为 180° 对角跳。
            case Y -> new WrenchTarget[]{
                new WrenchTarget(Direction.WEST, true),
                new WrenchTarget(Direction.NORTH, false),
                new WrenchTarget(Direction.EAST, true),
                new WrenchTarget(Direction.SOUTH, false)};
        };
        for (int i = 0; i < cycle.length; i++) {
            WrenchTarget t = cycle[i];
            if (t.facing() == facing && t.alongFirst() == alongFirst)
                return cycle[(i + 1) % cycle.length];
        }
        return null;
    }

    /**
     * 点上/下：沿当前倾侧偏航 90°（朝上环 x=0 / 朝下环 x=180），屏幕不会翻到另一侧，
     * 两环视觉方向一致（W→N→E→S，随 {@code getClockWise(Y)}；朝下环 2026-09-26 修正为同向）。
     * Y-face click: yaw 90° staying on the current tilt (up ring x=0 / down ring x=180) —
     * an inverted screen stays inverted, and both rings turn the same getClockWise way.
     */
    public static WrenchTarget nextInYaw(Direction facing, boolean alongFirst) {
        boolean downTilt = xRotation(facing, alongFirst) == 180;
        WrenchTarget[] ring = downTilt
            ? new WrenchTarget[]{ // 朝下环：down+false(down-W) → up+true(down-N) → up+false(down-E) → down+true(down-S)
                new WrenchTarget(Direction.DOWN, false),
                new WrenchTarget(Direction.UP, true),
                new WrenchTarget(Direction.UP, false),
                new WrenchTarget(Direction.DOWN, true)}
            : new WrenchTarget[]{ // 朝上环：west+false(up-W) → north+true(up-N) → east+false(up-E) → south+true(up-S)
                new WrenchTarget(Direction.WEST, false),
                new WrenchTarget(Direction.NORTH, true),
                new WrenchTarget(Direction.EAST, false),
                new WrenchTarget(Direction.SOUTH, true)};
        for (int i = 0; i < ring.length; i++) {
            WrenchTarget t = ring[i];
            if (t.facing() == facing && t.alongFirst() == alongFirst)
                return ring[(i + 1) % ring.length];
        }
        // 不在环上（不可达：环外只有 shaft_y 态，其 Y 面是轴端面走滚转）→ 进环起点兜底。
        // Not on a ring (unreachable: off-ring states are the shaft_y ones whose Y faces are
        // shaft ends) → enter the ring head as a fallback.
        return ring[0];
    }

    /**
     * 竖直轴 4 态走 {@code _shaft_y} 变体（north/south A=false、east/west A=true）。
     * 与 {@code blockstates/kinetic_gauge.json} 的模型选择逐项一致。
     * The 4 vertical-shaft states use the {@code _shaft_y} variant (north/south with
     * A=false, east/west with A=true) — mirrors the blockstate JSON's model choice.
     */
    public static boolean useShaftYVariant(Direction facing, boolean alongFirst) {
        return switch (facing) {
            case NORTH, SOUTH -> !alongFirst;
            case EAST, WEST -> alongFirst;
            default -> false;
        };
    }

    /**
     * 面板基矩阵：字形空间（x 右 / y 下 / 可读侧 −Z）→ 模型空间（居中于方块）。
     * Panel basis matrix: glyph space (x right / y down / readable side −Z) -> model units centred
     * in the block.
     *
     * <p><b>JOML 的 16 参数 {@code set(...)} 是列主序</b>（前 4 个参数填第 1 列），所以这里**按列分组**
     * 传入；写成"行主序"会把整个矩阵转置 —— 平移落进底行（透视行），GPU 做透视除法后顶点被 w 除成
     * 怪值，实机表现为"面条一路拉到相机"（2026-09-13 实证，见 {@code KineticGaugeStatesTest}）。</p>
     * <p>JOML's 16-argument {@code set(...)} is <b>column-major</b>, hence the per-column grouping.
     * Writing it row-major transposes the matrix, pushes the translation into the perspective row and
     * the GPU then divides vertices by w — "noodles stretching to the camera" in game.</p>
     *
     * <p>列 = {@code [right, −up, −normal, translation]}，平移为 {@code (cx−8, cy−8, cz−8)}（模型单位）。</p>
     * <p>Columns are {@code [right, −up, −normal, translation]} in model units.</p>
     */
    public static org.joml.Matrix4f panelBasis(Panel p) {
        return new org.joml.Matrix4f().set(
            p.rx(), p.ry(), p.rz(), 0f,
            -p.ux(), -p.uy(), -p.uz(), 0f,
            -p.nx(), -p.ny(), -p.nz(), 0f,
            p.cx() - 8f, p.cy() - 8f, p.cz() - 8f, 1f);
    }

    /**
     * blockstate x 旋转。
     * <p><b>横置四向（W/N/E/S）全部是 x=0 的上仰讲台姿态</b>：up-west / up-north /
     * up-east / up-south，这样点上/下绕 Y 偏航时屏幕四步都朝玩家、不会两步翻向
     * （2026-09 实测：「四个面向里有两个屏幕朝上/下反了」）。UP/DOWN 两族用 x=180
     * （倒置姿态，displayPanel 会把文字翻正）。</p>
     * <p>同一旋转轴的 4 个状态仍须 4 个互不重合的 (x,y)，否则绕轴扳手会卡步。</p>
     * <p>Blockstate x rotation. All four horizontal facings use x=0 (up-tilted
     * lectern), so a Y-face yaw shows the screen to the player on every step.
     * UP/DOWN use x=180 (inverted; displayPanel un-inverts the text). The four
     * states sharing a shaft axis still need four distinct (x,y) pairs.</p>
     */
    public static int xRotation(Direction facing, boolean alongFirst) {
        return facing.getAxis() == Direction.Axis.Y ? 180 : 0;
    }

    /**
     * blockstate y 旋转（与 JSON 表一致）。
     * 横置四向：W→0、N→90、E→180、S→270（上仰讲台绕 Y 转一圈）。
     * UP/DOWN 取剩余档位以保证同轴四态互不重合。
     * Blockstate y rotation. Horizontals: W→0, N→90, E→180, S→270 (one up-tilted
     * lectern yaw). UP/DOWN take the remaining slots so each shaft axis stays distinct.
     */
    public static int yRotation(Direction facing, boolean alongFirst) {
        return switch (facing) {
            case NORTH -> 90;
            case SOUTH -> 270;
            case EAST -> 180;
            case WEST -> 0;
            case UP -> alongFirst ? 90 : 180;
            case DOWN -> alongFirst ? 270 : 0;
        };
    }
}
