package io.github.y15173334444.create_schematic_compute.client.renderer;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.simibubi.create.content.kinetics.base.DirectionalAxisKineticBlock;
import com.simibubi.create.content.kinetics.base.DirectionalKineticBlock;
import io.github.y15173334444.create_schematic_compute.blocks.KineticGaugeBlockEntity;
import io.github.y15173334444.create_schematic_compute.blocks.KineticGaugeStates;
import io.github.y15173334444.create_schematic_compute.client.KineticShaftRenderer;
import io.github.y15173334444.create_schematic_compute.client.TransmissionVisual;
import io.github.y15173334444.create_schematic_compute.graph.EvalSnapshot;
import io.github.y15173334444.create_schematic_compute.graph.GraphNode;
import io.github.y15173334444.create_schematic_compute.graph.NodeGraph;
import io.github.y15173334444.create_schematic_compute.graph.NodeType;
import net.minecraft.client.gui.Font;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.blockentity.BlockEntityRenderer;
import net.minecraft.client.renderer.blockentity.BlockEntityRendererProvider;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.core.Direction;
import net.minecraft.world.level.block.state.BlockState;
import org.joml.Matrix4f;
import org.joml.Quaternionf;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * 动力仪表蓝屏渲染器：把「内置读数（转速 + 应力条）」或「图内 DATA/TEXT 节点」
 * 画到模型屏幕面上（与全息显示器同机制：图里有 DATA/TEXT 时显示它们，否则
 * 显示内置读数）。
 * Kinetic gauge blue-screen renderer: draws the built-in readout (speed + stress
 * bar) or the graph's DATA/TEXT nodes onto the model's screen face (same mechanism
 * as the holographic monitor: DATA/TEXT nodes when present, built-in readout
 * otherwise).
 *
 * <p><b>朝向约定（单一真相源 = {@link KineticGaugeStates}）</b>：
 * 模型有两个 authored 变体 —— 基础（落地/挂墙讲台屏，屏幕法线上仰 45°）与
 * {@code _shaft_y}（竖直轴，手绘的斜 45° 竖直屏，法线朝西北）。变体选择、blockstate 的
 * {@code x}（先）+ {@code y}（后）旋转、以及两个屏幕绘制锚点全部取自
 * {@link KineticGaugeStates} —— 它又必须与 {@code blockstates/kinetic_gauge.json}
 * （由 {@code tools/gen_gauge_assets.py} 生成）逐项一致，由
 * {@code KineticGaugeStatesTest} 钉死。BER 只负责复刻那套旋转（原版约定：从正轴看
 * 顺时针 = JOML 负角），再在模型空间里按锚点绘制 —— 文字永远与屏幕共面、朝向正确，
 * 「竖向放置时文字旋转」由同一套旋转自动解决。</p>
 * <p><b>Orientation contract (single source of truth = {@link KineticGaugeStates})</b>:
 * two authored variants — base (floor/wall lectern screen, normal tilted 45° up) and
 * {@code _shaft_y} (vertical shaft, hand-modelled 45°-yawed vertical panel facing north-west).
 * The variant choice, the
 * blockstate {@code x} (first) + {@code y} (second) rotations and both screen anchors all
 * come from {@link KineticGaugeStates}, which in turn must match
 * {@code blockstates/kinetic_gauge.json} (generated by {@code tools/gen_gauge_assets.py});
 * {@code KineticGaugeStatesTest} pins that down. The BER only replays that rotation
 * (vanilla convention: clockwise from the positive axis = negative JOML angle), then draws
 * in model space at each variant's anchor — text is always coplanar with the screen and
 * correctly oriented; "rotated text on vertical placement" falls out of the same rotation
 * automatically.</p>
 *
 * <p><b>数据面</b>：转速/应力/容量读 Create 已同步到客户端的网络字段（服务端权威，
 * 客户端不自算）；DATA 节点数值读服务端求值快照。全部自发光（不采样 lightmap）。</p>
 * <p><b>Data plane</b>: speed/stress/capacity read the Create-synced network fields
 * (server-authoritative, nothing recomputed client-side); DATA node values read the
 * server eval snapshot. Everything is emissive (no lightmap sampling).</p>
 */
public class KineticGaugeRenderer implements BlockEntityRenderer<KineticGaugeBlockEntity> {

    /** 全发光（与 Monitor 同）/ full-bright light (same as Monitor). */
    private static final int FULL_BRIGHT = 0xF000F0;

    /** 读数配色（本仓既有发光色系）/ readout palette (existing glow colours). */
    private static final int COL_GREEN = 0x7BFFA3;
    private static final int COL_YELLOW = 0xFBDC7D;
    private static final int COL_RED = 0xFFA7A4;
    private static final int COL_TEXT = 0xECF8FD;
    private static final int COL_DIM = 0x8FA6B5;
    private static final int COL_TRACK = 0x10222C;

    // 屏幕锚点与变体选择表已迁到单一真相源 KineticGaugeStates（详见类注释）。
    // Screen anchors and the variant table now live in KineticGaugeStates (see the class javadoc).

    public KineticGaugeRenderer(BlockEntityRendererProvider.Context context) {}

    @Override
    public void render(KineticGaugeBlockEntity be, float partialTick, PoseStack poseStack,
                       MultiBufferSource buffer, int light, int overlay) {
        BlockState state = be.getBlockState();
        if (!state.hasProperty(DirectionalKineticBlock.FACING))
            return;
        Direction facing = state.getValue(DirectionalKineticBlock.FACING);
        boolean alongFirst = state.getValue(DirectionalAxisKineticBlock.AXIS_ALONG_FIRST_COORDINATE);

        // 传动轴：本方块串联在动力网络里，必须画出穿过自身的旋转轴（相位与相邻官方轴一致）。
        // The shaft: this block sits in-line in a kinetic network, so it draws the shaft passing
        // through it, phase-aligned with neighbouring official shafts.
        renderGaugeShafts(be, poseStack, buffer, state, light);

        KineticGaugeStates.Panel panel = KineticGaugeStates.useShaftYVariant(facing, alongFirst)
            ? KineticGaugeStates.PANEL_SHAFT_Y : KineticGaugeStates.PANEL_BASE;

        // 复刻 blockstate 旋转：先 x 后 y，原版顺时针 = JOML 负角。
        // （q = Ry·Rx：顶点先被 Rx 再被 Ry 变换 —— 与 blockstate 的应用顺序一致。）
        // Replay the blockstate rotation: x first then y; vanilla CW = negative JOML.
        // (q = Ry·Rx: vertices see Rx first — matching the blockstate's order.)
        poseStack.pushPose();
        poseStack.translate(0.5, 0.5, 0.5);
        Quaternionf q = new Quaternionf()
            .rotationY((float) Math.toRadians(-KineticGaugeStates.yRotation(facing, alongFirst)));
        q.mul(new Quaternionf().rotationX((float) Math.toRadians(-KineticGaugeStates.xRotation(facing))));
        poseStack.mulPose(q);
        // 进入「模型单位」空间：模型 0..16 单位 = 1 方块 → ×1/16。
        // 面板锚点与字形比例都以模型单位给出；不换算的话文字会比方块大 16 倍、并被推到离方块
        // 4 格开外（2026-09-13 实测：屏幕上完全看不到参数）。
        // Enter model units (a 0..16 model spans one block). The anchors and the glyph scale are
        // expressed in model units; without this ×1/16 the text is 16× oversized and 16× too far
        // from the block (in-game report 2026-09-13: nothing visible on the screen).
        poseStack.scale(1f / 16f, 1f / 16f, 1f / 16f);

        // 面板基矩阵：**构造已抽到 KineticGaugeStates#panelBasis**（JOML 的 16 参数 set 是列主序，
        // 写错会整体转置 → 平移进透视行 → "面条拉到相机"）。这里只负责与 pose 相乘。
        // The basis construction lives in KineticGaugeStates#panelBasis (JOML's 16-arg set is
        // column-major; getting it wrong transposes the matrix and pushes the translation into the
        // perspective row). Here we only compose it with the pose.
        Matrix4f panelMat = new Matrix4f(poseStack.last().pose())
            .mul(KineticGaugeStates.panelBasis(panel));

        Font font = net.minecraft.client.Minecraft.getInstance().font;
        if (font == null)
            return;
        List<Line> lines = collectLines(be);
        if (lines.isEmpty())
            drawBuiltinReadout(be, font, buffer, panelMat, panel);
        else
            drawLines(font, buffer, panelMat, panel, lines);
        poseStack.popPose();
    }

    // ── 传动轴 / rotating shaft ──

    /**
     * 画出沿本方块旋转轴的两个轴端（与变速器/齿轮箱同款：复用它们的轴模型，已在
     * {@code ClientSetup} 注册为独立模型）。角度用官方相位公式，因此与相邻官方轴的相位一致。
     * Draws the two shaft ends along this block's rotation axis, reusing the transmission's shaft
     * models (registered standalone in ClientSetup) with the official phase formula.
     */
    private void renderGaugeShafts(KineticGaugeBlockEntity be, PoseStack poseStack, MultiBufferSource buffer,
                                   BlockState state, int light) {
        if (!(state.getBlock() instanceof DirectionalAxisKineticBlock axisBlock))
            return;
        Direction.Axis axis = axisBlock.getRotationAxis(state);
        BakedModel front = TransmissionVisual.FRONT_SHAFT.get();
        BakedModel rear = TransmissionVisual.REAR_SHAFT.get();
        BakedModel missing = net.minecraft.client.Minecraft.getInstance().getModelManager().getMissingModel();
        if (front == missing || rear == missing)
            return;
        // 仪表是贯通传轴，两端同速同相 / the gauge passes rotation through, so both ends share speed+phase.
        float angle = KineticShaftRenderer.angleFor(be.getLevel(), be.getBlockPos(), axis, be.getSpeed());
        KineticShaftRenderer.renderShaft(poseStack, buffer, state, front, axis, angle, light);
        KineticShaftRenderer.renderShaft(poseStack, buffer, state, rear, axis, angle, light);
    }

    // ── 内容收集 / content collection ──

    private record Line(String text, int color) {}

    /**
     * 图内有 DATA/TEXT 节点 → 逐行取值（服务端快照权威）；否则返回空表 → 内置读数。
     * With DATA/TEXT nodes present -> one line each (server snapshot authoritative);
     * empty list -> built-in readout.
     */
    private List<Line> collectLines(KineticGaugeBlockEntity be) {
        var lines = new ArrayList<Line>();
        NodeGraph graph = be.getNodeGraph();
        if (graph == null) return lines;
        EvalSnapshot snapshot = be.getCachedEvalSnapshot();
        boolean evalAvailable = be.isRunning() && snapshot != null;
        List<GraphNode> nodes = new ArrayList<>();
        for (var n : graph.nodes)
            if (n.type == NodeType.TEXT || n.type == NodeType.DATA) nodes.add(n);
        nodes.sort((a, b) -> {
            int c = Float.compare(a.layoutY, b.layoutY);
            return c != 0 ? c : Integer.compare(a.id, b.id);
        });
        for (var n : nodes) {
            if (n.type == NodeType.DATA && !evalAvailable) continue;
            String str = n.type == NodeType.DATA
                ? String.format(Locale.ROOT, "%.1f", graph.getInputValue(n.id, 0, snapshot.outputs()))
                : n.displayText;
            if (str == null || str.isEmpty()) continue;
            int color = n.textColor != 0 ? n.textColor
                : (n.type == NodeType.DATA ? 0xFF88FF88 : 0xFFCCCCCC);
            lines.add(new Line(str, color));
        }
        return lines;
    }

    // ── 内置读数 / built-in readout（坐标均为「上为正」的模型单位）──

    private void drawBuiltinReadout(KineticGaugeBlockEntity be, Font font,
                                    MultiBufferSource buffer, Matrix4f panelMat, KineticGaugeStates.Panel panel) {
        float speed = be.getGaugeSpeed();
        float stress = be.getGaugeStress();
        float cap = be.getGaugeCapacity();
        float ratio = cap > 0 ? stress / cap : 0f;
        float w = panel.halfRight();
        float h = panel.halfUp();
        boolean overloaded = ratio > 1f || be.isOverStressed();

        // 第 1 行：转速数字（右对齐）+ 小号 rpm 标签 / speed digits + small label.
        String num = String.format(Locale.ROOT, "%d", Math.round(speed));
        String label = "rpm";
        // 宽窗口（基础讲台屏）：rpm 与数字同行、放在数字左侧。
        // 窄窗口（竖屏，半宽 < 4.5）：rpm 放到**数字下方**——否则左侧标签会把可用宽度吃掉，
        // 字号被压得很小（2026-09-13 实测："RPM 字样和进度条还超出左右一点点"）。
        // Wide window: keep "rpm" inline to the left of the digits. Narrow window (portrait panel,
        // half-width < 4.5): put it **under** the digits, otherwise the inline label eats the width
        // budget and the glyph scale collapses.
        boolean labelInline = w >= 4.5f;
        float labelRatio = 0.6f;   // 标签字号 = 数字字号 × 0.6 / the label is 0.6× the digits
        float numScale;
        if (labelInline) {
            numScale = Math.min(0.24f, Math.min(
                (w * 2f - 1.05f) / Math.max(1f, font.width(num) + labelRatio * font.width(label)),
                h * 1.1f / 10f));
        } else {
            numScale = Math.min(0.24f, Math.min(
                (w * 2f - 0.75f) / Math.max(1f, font.width(num)),
                h * 1.1f / 10f));
        }
        float numH = 10f * numScale;
        float labelScale = Math.min(0.26f, numScale * labelRatio);
        float labelH = 10f * labelScale;
        // 标签在数字下方时多占一行（含 0.15 间隙）/ the stacked label adds one row (plus a 0.15 gap).
        float labelRow = labelInline ? 0f : (0.15f + labelH);
        float barHeight = Math.min(1.05f, h * 0.3f);
        float gap = 0.45f;
        float groupH = numH + labelRow + gap + barHeight;
        // 矮窗口（基础讲台屏）自上沿往下排；高窗口（竖直屏）把整组压在中间，避免两行被拉到上下两端。
        // Short window (lectern): lay the group out from the top edge. Tall window (vertical panel):
        // keep it one compact block around the centre instead of pinning the rows to the far edges.
        float numTop = (h * 2f > 8f) ? (groupH / 2f + 1.2f) : (h - 0.35f);
        float numX = w - 0.35f - font.width(num) * numScale;
        drawText(font, buffer, panelMat, num, numX, numTop, numScale, overloaded ? COL_RED : COL_TEXT);
        drawText(font, buffer, panelMat, label,
            labelInline ? (numX - 0.35f - font.width(label) * labelScale) : numX,
            labelInline ? (numTop - numH * 0.55f) : (numTop - numH - 0.15f),
            labelScale, COL_DIM);

        // 第 2 行：应力条 + 百分比（紧跟在数字/标签下方；百分比字号收窄到条高以内，不再压住条）。
        // Stress bar + percentage, directly under the digits/label; the percentage is scaled to the bar.
        float barBottom = numTop - numH - labelRow - gap - barHeight;
        // 百分比先算宽度，条尾给它让位 —— 窄窗口上不这么做，百分比会压在条尾上。
        // Compute the percentage first so the bar can leave room for it (on a narrow window they
        // otherwise overlap).
        String pct = String.format(Locale.ROOT, "%.0f%%", clampRatio(ratio) * 100);
        float pctScale = Math.min(0.16f, barHeight / 13f);
        float pctWidth = font.width(pct) * pctScale;
        float barX1 = Math.min(w - 2.1f, w - 0.4f - pctWidth - 0.3f);
        drawBar(buffer, panelMat, panel, -w + 0.4f, barX1, barBottom, barHeight, ratio, overloaded, be);
        float pctCenter = barBottom + barHeight / 2f;
        drawText(font, buffer, panelMat, pct,
            w - 0.4f - pctWidth,
            pctCenter + 5f * pctScale, pctScale, ratioColor(clampRatio(ratio)));
    }

    private void drawBar(MultiBufferSource buffer, Matrix4f panelMat, KineticGaugeStates.Panel panel,
                         float x0, float x1, float yBottom, float height, float ratio,
                         boolean overloaded, KineticGaugeBlockEntity be) {
        VertexConsumer vc = buffer.getBuffer(MonitorRenderTypes.SCREEN_PIXEL);
        float yTop = yBottom + height;
        quad(vc, panelMat, x0, x1, yBottom, yTop, 0f, COL_TRACK, 1f);
        // 填充与 Create 的 1.125 超载约定对齐：占比 1.125 才满条。
        // Fill aligned with Create's 1.125 overload convention: full bar at ratio 1.125.
        float fill = Math.max(0f, Math.min(ratio, 1.125f)) / 1.125f;
        if (fill <= 0f) return;
        float xFill = x0 + 0.12f + (x1 - x0 - 0.24f) * Math.min(fill, 1f);
        float alpha = overloaded && be.getLevel() != null
            && (be.getLevel().getGameTime() / 10) % 2 == 0 ? 0.35f : 1f;   // 超载闪烁 / blink
        quad(vc, panelMat, x0 + 0.12f, xFill, yBottom + 0.12f, yTop - 0.12f, -0.3f,
            ratioColor(clampRatio(ratio)), alpha);
    }

    /**
     * 面板平面四边形（坐标为「上为正」模型单位；zOut 负值朝观察者凸出；
     * {@link MonitorRenderTypes#SCREEN_PIXEL} 无背面剔除，绕序无关）。
     * Panel-plane quad (up-positive model units; negative zOut protrudes toward the
     * viewer; SCREEN_PIXEL has no culling so winding is irrelevant).
     */
    private void quad(VertexConsumer vc, Matrix4f panelMat,
                      float x0, float x1, float yBottom, float yTop, float zOut, int argb, float alpha) {
        float r = ((argb >> 16) & 0xFF) / 255f, g = ((argb >> 8) & 0xFF) / 255f, b = (argb & 0xFF) / 255f;
        // 面板矩阵的 y 轴是「字形向下」→ 这里取 −y 把「上为正」翻过去。
        // The panel matrix's y axis is glyph-down -> negate y here (up-positive input).
        vc.addVertex(panelMat, x0, -yTop, zOut).setColor(r, g, b, alpha);
        vc.addVertex(panelMat, x1, -yTop, zOut).setColor(r, g, b, alpha);
        vc.addVertex(panelMat, x1, -yBottom, zOut).setColor(r, g, b, alpha);
        vc.addVertex(panelMat, x0, -yBottom, zOut).setColor(r, g, b, alpha);
    }

    /**
     * 画一行字：{@code xLeft}/{@code yTop} 为字符串左上角的模型单位坐标（y 上为正、
     * 相对面板中心），{@code scale} 为每像素模型单位数。
     * Draws one line: {@code xLeft}/{@code yTop} = top-left of the string in model
     * units (y up, relative to the panel center), {@code scale} = model units per pixel.
     */
    private void drawText(Font font, MultiBufferSource buffer, Matrix4f panelMat,
                          String text, float xLeft, float yTop, float scale, int argb) {
        // 可读侧在字形 −Z → 先朝观察者抬 0.02 模型单位（像素空间里除以 scale），
        // 再落字符串左上角。像素→模型换算：先平移（像素）、后缩放（S）。
        // Readable side is glyph −Z -> lift 0.02 model units toward the viewer first,
        // then place the string's top-left. Pixel->model: translate (pixels) then scale.
        Matrix4f m = new Matrix4f(panelMat)
            .scale(scale, scale, scale)
            .translate(xLeft / scale, -yTop / scale, -0.02f / scale);
        font.drawInBatch(text, 0f, 0f, argb, false, m, buffer,
            Font.DisplayMode.NORMAL, 0, FULL_BRIGHT);
    }

    // ── DATA/TEXT 行布局 / line layout for DATA/TEXT nodes ──

    private void drawLines(Font font, MultiBufferSource buffer, Matrix4f panelMat,
                           KineticGaugeStates.Panel panel, List<Line> lines) {
        float w = panel.halfRight() * 2f - 0.8f;
        float availH = panel.halfUp() * 2f - 0.8f;
        int n = Math.min(lines.size(), 6);
        float lineH = availH / n;
        // 行高约束 + 最宽行约束，取最小字号 / fit by line height and widest line
        float scale = Math.min(0.5f, (lineH - 0.15f) / 10f);
        float maxW = 0;
        for (int i = 0; i < n; i++) maxW = Math.max(maxW, font.width(lines.get(i).text()));
        if (maxW > 0) scale = Math.min(scale, w / maxW);
        for (int i = 0; i < n; i++) {
            Line line = lines.get(i);
            float yTop = panel.halfUp() - 0.4f - i * lineH;
            drawText(font, buffer, panelMat, line.text(), -panel.halfRight() + 0.4f,
                yTop - 10f * scale, scale, line.color());
        }
    }

    // ── 小工具 / helpers ──

    private static float clampRatio(float r) { return Math.max(0f, Math.min(r, 1f)); }

    /** 比例色：0→绿，0.6→黄，1→红（本仓发光色系）。 Ratio colour: green→yellow→red. */
    private static int ratioColor(float r) {
        if (r < 0.6f) return mix(COL_GREEN, COL_YELLOW, r / 0.6f);
        return mix(COL_YELLOW, COL_RED, (r - 0.6f) / 0.4f);
    }

    private static int mix(int a, int b, float t) {
        t = Math.max(0f, Math.min(1f, t));
        int ar = (a >> 16) & 0xFF, ag = (a >> 8) & 0xFF, ab = a & 0xFF;
        int br = (b >> 16) & 0xFF, bg = (b >> 8) & 0xFF, bb = b & 0xFF;
        return (0xFF << 24)
            | ((int) (ar + (br - ar) * t) << 16)
            | ((int) (ag + (bg - ag) * t) << 8)
            | (int) (ab + (bb - ab) * t);
    }

    // blockstate 旋转表与变体选择已迁到 KineticGaugeStates（单一真相源，见类注释）。
    // The blockstate rotation table and variant choice moved to KineticGaugeStates.
}
