package io.github.y15173334444.create_schematic_compute.graph;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * 火控弹道反解脚本测试(v2,对照 CreateBigCannons 5.11.x tick 模型金标准)。
 * 脚本:docs/examples/ballistic_solver.formula — 粗扫描(46 点 × 4°)+ 细扫(0.5°)+ 割线精化(≤10 轮),
 * 线段碰撞判定对齐游戏内 raycast;参数已内化(7 系炮 · 8 装药 · HE/AP 弹:v0=160 b/s、g=20 b/s²、fd=0.2)。
 * 期望值由 CBC tick 半隐式欧拉金标准对拍器生成(2026-10-06,落点误差 ≤0.24 格)。
 * Fire-control ballistic inverse-solver test (v2, validated against the CreateBigCannons 5.11.x
 * tick-model golden reference). Script: docs/examples/ballistic_solver.formula — coarse scan
 * (46 pts × 4°) + fine scan (0.5°) + secant refinement (≤10 rounds), segment-based hit test
 * matching the in-game raycast; parameters baked in (size-7 barrel · 8 charges · HE/AP shell:
 * v0=160 b/s, g=20 b/s², fd=0.2). Expected values generated by the CBC tick-model cross-checker.
 */
class BallisticSolverTest {

    private static String loadScript() {
        try {
            return Files.readString(Path.of("docs/examples/ballistic_solver.formula"));
        } catch (Exception e) {
            fail("cannot read docs/examples/ballistic_solver.formula: " + e);
            return null;
        }
    }

    /** 以输入运行脚本(v2 仅炮口/目标 6 引脚),返回 [ay, ap, hit] / run the script, returns [ay, ap, hit]. */
    private static double[] solve(double mx, double my, double mz,
                                  double tx, double ty, double tz) {
        var parsed = FormulaParser.parseScript(loadScript());
        assertNotNull(parsed.ast, "script must parse to AST mode; issues: " + parsed.issues);
        assertTrue(parsed.issues.isEmpty(), "script issues: " + parsed.issues);
        var env = new HashMap<String, Value>();
        env.put("mx", new Value.Scalar(mx)); env.put("my", new Value.Scalar(my)); env.put("mz", new Value.Scalar(mz));
        env.put("tx", new Value.Scalar(tx)); env.put("ty", new Value.Scalar(ty)); env.put("tz", new Value.Scalar(tz));
        FormulaInterpreter.exec(parsed.ast, env);
        return new double[]{
            FormulaParser.asScalar(env.get("ay")),
            FormulaParser.asScalar(env.get("ap")),
            FormulaParser.asScalar(env.get("hit")),
            FormulaParser.asScalar(env.get("vx0")),
            FormulaParser.asScalar(env.get("vy0")),
            FormulaParser.asScalar(env.get("vz0"))
        };
    }

    @Test
    @DisplayName("ballistic: close flat shot 250 blocks (CBC golden: yaw=83.1572, pitch=7.8086, hit)")
    void testCaseClose() {
        double[] r = solve(0, 80, 0, 250, 82, -30);
        assertEquals(83.1572, r[0], 0.5, "yaw");
        assertEquals(7.8086, r[1], 0.3, "pitch");
        assertEquals(1.0, r[2], 0.0, "hit");
    }

    @Test
    @DisplayName("ballistic: mid-range 500 blocks with drag (CBC golden: yaw=78.6901, pitch=28.3211, hit)")
    void testCaseMidRange() {
        double[] r = solve(0, 80, 0, 500, 70, -100);
        assertEquals(78.6901, r[0], 0.5, "yaw");
        assertEquals(28.3211, r[1], 0.3, "pitch");
        assertEquals(1.0, r[2], 0.0, "hit");
    }

    @Test
    @DisplayName("ballistic: downward over height gap (CBC golden: yaw=90, pitch=-11.0100, hit)")
    void testCaseDownward() {
        double[] r = solve(0, 200, 0, 400, 20, 0);
        assertEquals(90.0, r[0], 0.5, "yaw");
        assertEquals(-11.0100, r[1], 0.3, "pitch");
        assertEquals(1.0, r[2], 0.0, "hit");
    }

    @Test
    @DisplayName("ballistic: near-vertical shot (CBC golden: yaw=90, pitch=88.3990, hit)")
    void testCaseVertical() {
        double[] r = solve(0, 80, 0, 3, 190, 0);
        assertEquals(90.0, r[0], 0.5, "yaw");
        assertEquals(88.3990, r[1], 0.3, "pitch");
        assertEquals(1.0, r[2], 0.0, "hit");
    }

    @Test
    @DisplayName("ballistic: out-of-range target reports hit=0")
    void testCaseOutOfRange() {
        double[] r = solve(0, 80, 0, 3000, 50, 0);
        assertEquals(90.0, r[0], 0.5, "yaw");
        assertEquals(0.0, r[2], 0.0, "hit must be 0 beyond max range");
    }

    @Test
    @DisplayName("ballistic: script parses clean (no issues) and pin count matches v2")
    void testScriptParsesClean() {
        var parsed = FormulaParser.parseScript(loadScript());
        assertNotNull(parsed.ast);
        assertTrue(parsed.issues.isEmpty(), "issues: " + parsed.issues);
        assertEquals(6, parsed.inputVars.size(), "6 input pins (muzzle/target)");
        assertEquals(6, parsed.outputLabels.size(), "6 outputs (ay/ap/hit/vx0/vy0/vz0)");
    }
}
